#!/usr/bin/env bash
# This script displays information for subdomains of an address
print_domain_info()
{
	command=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION' | tail -n 1)
	echo "$2 $command" | awk '{print "The subdomain " $1 " is a " $5 " record and points to " $6}'
}

if [ $# -eq 1 ]
then
	print_domain_info "$1" "www"
	print_domain_info "$1" "lb-01"
	print_domain_info "$1" "web-01"
	print_domain_info "$1" "web-02"
elif [ $# -eq 2 ]
then
	print_domain_info "$1" "$2"
fi
