#!/usr/bin/env bash

print_domain_info() {
  local domain="$1"
  local subdomain="$2"
  
  local record_type
  local destination
  
  case $subdomain in
    www)
      record_type="CNAME"
      destination="lb-01"
      ;;
    lb-01)
      record_type="A"
      destination="lb-01-IP"
      ;;
    web-01)
      record_type="A"
      destination="web-01-IP"
      ;;
    web-02)
      record_type="A"
      destination="web-02-IP"
      ;;
    *)
      echo "Invalid subdomain: $subdomain"
      return
      ;;
  esac
  
  echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

if [ $# -eq 1 ]; then
  domain="$1"
  print_domain_info "$domain" "www"
  print_domain_info "$domain" "lb-01"
  print_domain_info "$domain" "web-01"
  print_domain_info "$domain" "web-02"
elif [ $# -eq 2 ]; then
  domain="$1"
  subdomain="$2"
  print_domain_info "$domain" "$subdomain"
else
  echo "Invalid number of arguments"
fi
