#!/usr/bin/env bash
# installs nginx &  configures it on a remote server

sudo apt-get update -y
sudo apt-get install nginx -y
sudo sed -i 's/.*listen 80 default_server;/listen 80 default_server;/' /etc/nginx/sites-available/default
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart
